on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CTest
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ctest